GET http://localhost:8090

###
GET http://localhost:8090/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyRW1haWwiOiJtYW5vMTFAZXhhbXBsZS5jb20iLCJzdWIiOnsibmFtZSI6Ik1hbm8gdGVzdGUtMTEifSwiaWF0IjoxNjk0OTMwNjA3LCJleHAiOjE2OTQ5MzQyMDd9.d0VsaFlDcAYpyBBi6VfrkfUJlAtHAhqPVhh7mZI0nYE


###
GET http://localhost:8090/users/4

###
POST  http://localhost:8090/users
Content-Type: application/json

{
    "name": "Mano teste-0",
    "email": "mano0@example.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
PATCH   http://localhost:8090/users/1
Content-Type: application/json

{
    "email": "mano@example.com",
    "name": "Mano teste-1 update",
    "password": "123456"
}

###
DELETE    http://localhost:8090/users/14
Content-Type: application/json

###
POST  http://localhost:8090/auth-token/login
Content-Type: application/json

 {
    "email": "mano11@example.com",
    "password": "123456"
 }

###
POST  http://localhost:8090/auth-token/register
Content-Type: application/json

{
    "name": "Mano teste-11",
    "email": "mano11@example.com",
    "password": "123456",
    "confirmPassword": "123456"
}